//%attributes = {}
Begin SQL
	
	CREATE TABLE IF NOT EXISTS EVENEMENT (
	
	ID INT32 AUTO_INCREMENT PRIMARY KEY,
	Libelle VARCHAR NOT NULL,
	Date_debut TIMESTAMP NOT NULL,
	Date_fin TIMESTAMP NOT NULL
	
	);
	
End SQL